# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: IDeSyDe
email: jordao@kth.se
description: >- # this means to ignore newlines until "baseurl:"
  Design space identification and exploration
# baseurl: "/IDeSyDe" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
parent-url: https://forsyde.github.io
# twitter_username: jekyllrb
github_username: forsyde

projects:
  forsyde: https://forsyde.github.io
  forsydeio: https://forsyde.github.io/forsyde-io
  idesyde: https://forsyde.github.io/IDeSyDe
sources:
  forsydeio: https://github.com/forsyde/forsyde-io
  idesyde: https://github.com/forsyde/IDeSyDe

# Build settings
remote_theme: forsyde/forsyde-web-theme
# remote_theme: aksakalli/jekyll-doc-theme@gh-pages   
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# remote_theme: just-the-docs/just-the-docs
#theme: "just-the-docs"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Extra configuration
# logo: "https://forsyde.github.io/assets/images/forsyde-logo.svg"
aux_links:
  '<img src="https://forsyde.github.io/assets/images/forsyde-logo.svg" height="40" width="60"/>':
  - "https://forsyde.github.io"
  '<img src="https://cdn.worldvectorlogo.com/logos/github-icon.svg" height="40" width="40"/>':
  - "https://github.com/forsyde/IDeSyDe"
color_scheme: "light"
